#!/usr/bin/env bash

# Default prompt (e.g. [~/Documents/Repos/dotfiles] $ ).
PS1="[\w] $ "

# Liquid Prompt (brew install liquidprompt)
if [ -f "$(brew --prefix)/share/liquidprompt" ]; then
    # Only load Liquid Prompt in interactive shells (not from a script or scp)
    [[ $- = *i* ]] && source "$(brew --prefix)/share/liquidprompt"
fi
