#!/usr/bin/env bash

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

# Determine the real path of this file
# so that it can be sourced from anywhere.
SOURCE="${BASH_SOURCE[0]}"

# Resolve $SOURCE until the file is no longer a symlink.
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"

  # If $SOURCE was a relative symlink, we need to resolve it
  # relative to the path where the symlink file was located.
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done

# This is the real path to this file.
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Basic dotfiles.
source $DIR/bash_exports
source $DIR/bash_aliases
source $DIR/bash_prompt
source $DIR/bash_paths
source $DIR/functions/*

# Bash tab completion.
if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    source "$(brew --prefix)/etc/bash_completion"
fi

# Virtual environment wrapper.
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

# Local and private settings (e.g. git credentials).
if [ -f $HOME/.bash_profile.local ]; then
    source $HOME/.bash_profile.local
fi

unset SOURCE
unset DIR
