#!/usr/bin/env bash

# Default prompt (e.g. [~/Documents/Repos/dotfiles] $ ).
PS1="[\w] $ "

# Bash-Git-Prompt (brew install bash-git-prompt)
#if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
#    source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
#    GIT_PROMPT_ONLY_IN_REPO=1
#    GIT_PROMPT_THEME=Custom
#fi

# Liquid Prompt (brew install liquidprompt)
if [ -f "$(brew --prefix)/share/liquidprompt" ]; then
    # Only load Liquid Prompt in interactive shells (not from a script or scp)
    [[ $- = *i* ]] && source "$(brew --prefix)/share/liquidprompt"
fi
