# Determine the real path of this file so that it can be sourced from anywhere.
SOURCE=${(%):-%N}

# Resolve $SOURCE until the file is no longer a symlink.
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"

  # If $SOURCE was a relative symlink, we need to resolve it
  # relative to the path where the symlink file was located.
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

# This is the real path to this file.
DOTFILES_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

unset SOURCE
unset DIR

# Load antigen.
source $DOTFILES_DIR/antigen.zsh

# Load oh-my-zsh.
antigen use oh-my-zsh

# Bundles from oh-my-zsh.
antigen bundle git
antigen bundle extract
antigen bundle jsontools
antigen bundle vi-mode
antigen bundle httpie
antigen bundle docker
antigen bundle docker-compose
antigen bundle golang
antigen bundle python
antigen bundle pip
antigen bundle pyenv
antigen bundle aws

# Custom bundles.
antigen bundle gangleri/pipenv
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async

# Set theme.
antigen bundle sindresorhus/pure
antigen theme sindresorhus/pure

# Tell antigen that we're done.
antigen apply

# Don't share history.
unsetopt share_history

# Make neovim the default editor.
export VISUAL=nvim
export EDITOR="$VISUAL"

# Don't clear the screen after quitting a man page.
export MANPAGER="less -X"

# Paths.
export GOPATH="$HOME/workspace/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="$(brew --prefix)/sbin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix findutils)/libexec/gnubin:$PATH"
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
export MANPATH="$(brew --prefix findutils)/libexec/gnuman:$MANPATH"

# Tell pipenv to install virtual environments in the root of the project.
export PIPENV_VENV_IN_PROJECT=true

# GPG
export GPG_TTY=$(tty)

# Aliases.
alias ls="ls -lF --color --group-directories-first"
alias la="ls -lAF --color --group-directories-first"
alias cls="clear; ls"
alias ag='ag --color-match "0;31" --pager "less -FRSX"'
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} --exclude='*.pyc'"
alias ping="prettyping --nolegend"
alias py="python"
alias ipy="ipython"
alias rb="ruby"
alias vim="nvim"

# Increase the max number of open file descriptors allowed.
ulimit -n 4096

# Enable aws cli tab completion.
autoload -Uz compinit && compinit
autoload -Uz bashcompinit
bashcompinit -i
complete -C aws_completer aws
