# Show timestamps in zsh history.
HIST_STAMPS="mm/dd/yyyy"

# Enable aws cli tab completion.
autoload -Uz compinit && compinit
autoload -Uz bashcompinit
bashcompinit -i
complete -C aws_completer aws

# Launch pure prompt.
autoload -U promptinit && promptinit
prompt pure

# Don't share history.
unsetopt share_history

# Make neovim the default editor.
export VISUAL=nvim
export EDITOR="$VISUAL"

# Don't clear the screen after quitting a man page.
export MANPAGER="less -X"

# Paths.
export GOPATH="$HOME/go"
export GOROOT="$(brew --prefix)/opt/go/libexec"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$GOROOT/bin"
export PATH="$(brew --prefix)/sbin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Ansible
export ANSIBLE_VAULT_PASSWORD_FILE="~/.ansible/vault-pass.txt"

# Aliases.
alias ls="ls --color -G"
alias cls="clear; ls"
alias py="python"
alias ipy="ipython"
alias rb="ruby"
alias docker_prune_images="docker images | awk '/<none>/ { print $3 }' | xargs docker rmi"
alias docker_prune_containers="docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm"
alias vim="nvim"
alias ag='ag --color-match "0;31" --pager "less -FRSX"'
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} --exclude='*.pyc'"

# Increase the max number of open file descriptors allowed.
ulimit -n 4096

# Initialize pyenv and pyenv-virtualenv.
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
