# Determine the real path of this file so that it can be sourced from anywhere.
SOURCE=${(%):-%N}

# Resolve $SOURCE until the file is no longer a symlink.
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"

  # If $SOURCE was a relative symlink, we need to resolve it
  # relative to the path where the symlink file was located.
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

# This is the real path to this file.
DOTFILES_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
unset DIR

# Path to oh-my-zsh.
export ZSH=$DOTFILES_DIR/oh-my-zsh

# zsh theme.
ZSH_THEME="robbyrussell"

# zsh plugins.
plugins=(
    git
    jira
    python
    virtualenv
    virtualenvwrapper
    colorize
    docker
    docker-compose
    extract
    themes
    vi-mode
    zsh_reload
    colored-man-pages
    copydir
    copyfile
)

# Show timestamps in zsh history.
HIST_STAMPS="mm/dd/yyyy"

# Start oh-my-zsh.
source $ZSH/oh-my-zsh.sh

# Make neovim the default editor.
export VISUAL=nvim
export EDITOR="$VISUAL"

# Docker configuration.
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="$HOME/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

# Don't clear the screen after quitting a man page.
export MANPAGER="less -X"

# Paths.
export PATH="$(brew --prefix)/sbin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# JIRA command line.
export JIRA_URL="https://my.rewardstyle.com"
export JIRA_NAME="nathan.phetteplace"

# Aliases.
alias ls="ls --color -G"
alias py="python"
alias ipy="ipython"
alias rb="ruby"
alias docker_prune_images="docker images | awk '/<none>/ { print $3 }' | xargs docker rmi"
alias vim="nvim"
alias ag='ag --color-match "0;31" --pager "less -FRSX"'
alias grep="--color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} --exclude='*.pyc'"

# Increase the max number of open file descriptors allowed.
ulimit -n 4096
